name = "pesde/not_for_publish"
version = "0.0.0"
private = true

[target]
environment = "lune"

[indices]
default = "https://github.com/daimond113/pesde-index"

[engine]
lune = "0.8.9"
pesde = "0.7.0-rc.1"

[dev_dependencies]
frktest = { name = "itsfrank/frktest", version = "^0.0.2" }
base64 = { name = "synpixel/base64", version = "^3.0.1" }
